### PR TITLE
fix(combobox): Add keyboard navigation autoscroll to ComboBox menu

### LINKED ISSUE #1251: Combobox menu items do not scroll into focus on keyboard navigation
## 🐛 Bug Report

Combobox menu items do not scroll into focus on keyboard navigation.

## To Reproduce

- visit [this sandbox]
- navigate down to items in the list using a keyboard
- see how the menu does not scroll items into focus

## Actual Results

Focus continues down the list list items, but is no longer visible

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/wine-combobox-example-forked-2wk6p?file=/src/App.tsx

## Screenshot

combobox menu bug

### PR DESCRIPTION
**Pull request by BillGeoghegan**
## Summary

Fixes #1251

Fix for scrolling with keyboard navigation in the ComboBox. 

category

## Checklist

- [X] branch has been rebased on the latest master commit
- [X] tests are changed or added `(N/A)`
- [X] `yarn test` passes
- [X] all (dev)dependencies that the module needs is added to its `package.json`
- [X] code has been documented and, if applicable, usage described in README.md
- [X] module has been added to `canvas-kit-react` and/or `canvas-kit-css` universal modules, if
      applicable `(N/A)`
- [X] design approved final implementation `(N/A)`
- [ ] a11y approved final implementation
- [ ] code adheres to the [API & Pattern guidelines](../modules/docs/mdx/API_PATTERN_GUIDELINES.mdx)

## Additional References

- [Example of issue here](https://codesandbox.io/s/wine-combobox-example-forked-2wk6p?file=/src/App.tsx)
  - Navigate down the list using keyboard inputs
  - Note that it **doesn't** scroll when it gets to the bottom
  image

### CODE REVIEW

**Review by NicholasBoll — APPROVED** [review]

File: modules/labs-react/combobox/lib/AutocompleteList.tsx [hunk 1]
```diff
@@ -7,8 +7,10 @@ import {ComboBoxMenuItemGroup, getOptionId, listBoxIdPart, getTextFromElement} f
 import uuid from 'uuid/v4';
 
 const Autocomplete = styled('ul')({
-  padding: 0,
-  margin: `${space.xxs} 0`,
+  margin: 0,
+  maxHeight: 184,
```
Comment (alanbsmith) [inline modules/labs-react/combobox/lib/AutocompleteList.tsx:11]: I don't think we want to change the `maxHeight` to 184 here. 200px is our standard `maxHeight` for [Menu](https://github.com/Workday/canvas-kit/blob/fa0f4d9226ada17cbd9f293eb914313d94d966d8/modules/preview-react/select/lib/SelectMenu.tsx#L160), [Combobox](https://github.com/Workday/canvas-kit/blob/3123cc7bbb0f81d3a94e6b4cd3cec3c939243564/modules/labs-react/combobox/lib/Combobox.tsx#L108), and [Dropdown](https://github.com/Workday/canvas-kit/blob/6578fc3c90f53e0afda308733858b2d3967a34bf/modules/preview-react/breadcrumbs/lib/Breadcrumbs/Dropdown/Menu.tsx#L63).

Comment (alanbsmith) [reply modules/labs-react/combobox/lib/AutocompleteList.tsx:11]: Oh wait. I'm looking closer now, and I see the issue.

File: modules/labs-react/combobox/lib/AutocompleteList.tsx [hunk 2]
```diff
@@ -7,8 +7,10 @@ import {ComboBoxMenuItemGroup, getOptionId, listBoxIdPart, getTextFromElement} f
...
+  overflowY: 'scroll',
```
Comment (alanbsmith) [inline modules/labs-react/combobox/lib/AutocompleteList.tsx:12]: I think this should be `overflowY: 'auto'` so we don't always see the scrollbar unless it's needed.

```suggestion
  overflowY: 'auto',
```

File: modules/labs-react/combobox/lib/AutocompleteList.tsx (hunk 1 above)
Comment (alanbsmith) [reply modules/labs-react/combobox/lib/AutocompleteList.tsx:11]: I'm going to ask our designers what they think about compensating the height for the padding.

File: modules/labs-react/combobox/stories/stories.tsx [hunk 3]
```diff
@@ -39,7 +39,7 @@ const groupOfResults = (
       <strong>{groupHeading}</strong>
     </MenuItem>
   ),
-  items: simpleAutoComplete(count, showDisabledItems, 3),
+  items: simpleAutoComplete(count, showDisabledItems, 10),
```
Comment (alanbsmith) [inline modules/labs-react/combobox/stories/stories.tsx:42]: 👍🏻 Thanks for adding this.

File: modules/labs-react/combobox/lib/AutocompleteList.tsx (hunk 1 above)
Comment (alanbsmith) [reply modules/labs-react/combobox/lib/AutocompleteList.tsx:11]:
```suggestion
  maxHeight: 200,
  boxSizing: 'border-box',
```

The reason you needed to adjust the `maxHeight` was because the `boxSIzing` wasn't set to `border-box`. If we do that, we can keep it at 200 and everything renders as we'd expect.

I was able to reproduce it here:
autocomplete menu scrolling

**Review by alanbsmith — CHANGES_REQUESTED** [review]
Thanks for the fix!

I suggested a couple minor tweaks, but otherwise, this looks great! Thanks again!

**Review by alanbsmith — COMMENTED** [review]
Looks great, @BillGeoghegan! Thanks for the fix! 🎉

**Review by alanbsmith — APPROVED** [review]
