### PR TITLE
fix(menu): Update MenuItem icon styles

### LINKED ISSUE #851: Labs MenuItem does not take icons into account for the width.
## 🐛 Bug Report

The width of the Menu component does not seem to properly take icons into account.

## To Reproduce

Create a menu with an icon that has text content that is longer than any other item in the menu.

## Expected Behavior

The menu would expand to display the entire content (assuming the menu item is a sentence of text).

## Actual Results

Even a small amount of text ends up being cut off / ellipsis. 

## Browser (if applicable)

Not browser specific.

Screen Shot 2020-09-01 at 4 48 41 PM

Proposed solution: change the Menu Item style from `flex: ${iconSize + iconPadding}px 0` to `width: iconSize + iconPadding`, as suggested by @jamesfan

### PR DESCRIPTION
**Pull request by alanbsmith**
## Issue

Fixes #851 

## Overview

This PR updates the MenuItem styles in the Labs Menu component to keep consistent spacing around icons. I also updated and added a visual test. And I verified that the CSS version of the Menu component does not have this issue.

## Where Should the Reviewer Start?

`modules/_labs/menu/react/lib/MenuItem.tsx`

## Testing Manually

* pull down this branch locally
* run `yarn start`
* visit `http://localhost:9001/?path=/story/labs-menu-react--with-icons`
* visit `http://localhost:9001/?path=/story/testing-react-labs-menu--menu-item-states`

## New Dependencies

n/a

### Before 😿 

Screen Shot 2020-10-14 at 3 41 12 PM

### After 🥳 

Screen Shot 2020-10-14 at 4 12 24 PM

## Thank You Gif
_Share a fun [gif](https://giphy.com) to say thanks to your reviewer:_

## Checklist

- [ ] branch has been rebased on the latest master commit
- [ ] tests are changed or added
- [ ] `yarn test` passes
- [ ] all (dev)dependencies that the module needs is added to its `package.json`
- [ ] code has been documented and, if applicable, usage described in README.md
- [ ] module has been added to `canvas-kit-react` and/or `canvas-kit-css` universal modules, if
      applicable
- [ ] design approved final implementation
- [ ] a11y approved final implementation
- [ ] code adheres to the [API & Pattern guidelines](../API_PATTERN_GUIDELINES.md)

### CODE REVIEW

File: modules/_labs/menu/react/lib/MenuItem.tsx [hunk 1]
```diff
@@ -137,11 +137,14 @@ const Divider = styled('hr')({
 const iconSize = 24;
 const iconPadding = 16;
 const StyledSystemIcon = styled(SystemIcon)({
-  flex: `${iconSize + iconPadding}px 0`, // gives padding between LabelContainer, no matter the direction
+  flexShrink: 0,
+  flexBasis: iconSize + iconPadding, // gives padding between LabelContainer, no matter the direction
 });
 
-const SecondaryStyledSystemIcon = styled(StyledSystemIcon)({
+const SecondaryStyledSystemIcon = styled(SystemIcon)({
```
Comment (alanbsmith) [inline modules/_labs/menu/react/lib/MenuItem.tsx:144]: It seemed odd to extend the style of the first `StyledSystemIcon`, so I added the styles directly instead.

File: modules/_labs/menu/react/stories/stories.tsx [hunk 2]
```diff
@@ -33,7 +33,7 @@ const createMenuItems = (hasIcons?: boolean): StoryMenuItemProps[] => {
       icon: hasIcons ? uploadCloudIcon : undefined,
     },
     {
-      text: `Second Item with really really really long label`,
+      text: `Second Item (with a really really really long label)`,
```
Comment (alanbsmith) [inline modules/_labs/menu/react/stories/stories.tsx:36]: Parentheses were added to keep visual consistency with the other labels, and the "a" was added as a grammar check. 😄

File: modules/_labs/menu/react/stories/stories_visualTesting.tsx [hunk 3]
```diff
@@ -33,11 +33,20 @@ const createMenuItems = (hasIcons?: boolean, isFocused?: boolean): StoryMenuItem
...
     {
-      text: `Third Item (disabled)`,
+      text: `Third Item (with a really really really long label)`,
+      icon: hasIcons ? uploadCloudIcon : undefined,
+    },
+    {
+      text: `Fourth Item (with a really really really long label)`,
+      icon: hasIcons ? uploadCloudIcon : undefined,
+      secondaryIcon: hasIcons ? extLinkIcon : undefined,
+    },
```
Comment (alanbsmith) [inline modules/_labs/menu/react/stories/stories_visualTesting.tsx:47]: Part of the reason we missed this (I think) is because we didn't have a visual test for it. Though we have a story that shows the issue, they aren't inspected as closely as the visual regression tests.

File: modules/_labs/menu/react/stories/stories_visualTesting.tsx [hunk 4]
```diff
@@ -33,11 +33,20 @@ const createMenuItems = (hasIcons?: boolean, isFocused?: boolean): StoryMenuItem
       isFocused: isFocused,
     },
     {
-      text: `Second Item with really really really long label`,
+      text: `Second Item (with a really really really long label)`,
```
Comment (alanbsmith) [inline modules/_labs/menu/react/stories/stories_visualTesting.tsx:36]: Parentheses were added to keep visual consistency with the other labels, and the "a" was added as a grammar check. 😄

File: modules/_labs/menu/react/stories/stories_visualTesting.tsx [hunk 5]
```diff
@@ -47,14 +56,14 @@ const createMenuItems = (hasIcons?: boolean, isFocused?: boolean): StoryMenuItem
         ''
       ) : (
         <em>
-          Fourth Item (<b>with markup</b>)
+          Sixth Item (<b>with markup</b>)
         </em>
       ),
-      icon: undefined,
+      icon: hasIcons ? userIcon : undefined,
```
Comment (alanbsmith) [inline modules/_labs/menu/react/stories/stories_visualTesting.tsx:62]: This was added to be consistent with the other story. This was previously rendering an empty item in the menu and was confusing.

**Review by NicholasBoll — APPROVED** [review]

**Comment by NicholasBoll** [comment]
I noticed the IE11 screenshot did not ellipsis the 4th item in the icon version like the other browsers did. I wasn't sure if this was intentional: https://www.chromatic.com/component?appId=5d854c26ba934e0020f5e98a&name=Testing%7CReact%2FLabs%2FMenu&buildNumber=2275&specName=Menu+Item+States&mode=snapshot&viewport=1200&browser=ie

**Comment by NicholasBoll** [comment]
Chrome:
image

IE11:
image

**Comment by alanbsmith** [comment]
@NicholasBoll, that's odd. I wonder if it's ever truncated in IE.

**Review by jamesfan — APPROVED** [review]
