### PR TITLE
fix: Update `useReturnFocus` to change focus if target is visible

### LINKED ISSUE #1436: useReturnFocus can scroll page when clicking outside
## 🐛 Bug Report

A popup using `useCloseOnOutsideClick` and `useReturnFocus` will scroll to the `Popup.Target` element when scrolling away from the popup while it is open and clicking outside the popup.

## To Reproduce

Open the linked code sandbox and follow the instructions.

## Expected Behavior

The browser should not change the scroll position.

## Actual Results

A clear and concise description of what actually happens

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/popup-click-outside-focus-c6dhy

### Error Output

PopupClickScroll

### PR DESCRIPTION
**Pull request by NicholasBoll**
## Summary

Fixes #1436
Also fixes issue in #1437, but doesn't implement `useCloseOnScroll`

`useReturnFocus` will now check if the target is rendered onscreen and if the user clicked on a focusable element. It will not return focus to the target in these cases.

category

---

## Checklist

- [x] MDX documentation adheres to Canvas Kit's [standard MDX template](https://github.com/Workday/canvas-kit/discussions/1131)

## For the Reviewer

- [x] PR title is short and descriptive
- [x] PR summary describes the change (Fixes/Resovles linked correctly)
- [x] PR Release Notes describes additional information useful to call out in a release message or removed if not applicable
- [x] Breaking Changes provides useful information to upgrade to this code or removed if not applicable

## Where Should the Reviewer Start?

Extra heuristics were added to `useReturnFocus` when focus is meant to be returned. If the user clicks outside a popup, the element that is clicked on is checked to see if it is a focusable element. If it is a focusable element, `useReturnFocus` will _not_ return focus. This fixes the issue where focus is "stolen". Not returning focus when the target element is off screen fixes the issue where scrolling "snaps back" to the target.

## Testing Manually

Go to the new "Return Focus Test" and follow the instructions. Also automated tests verify functionality.

### CODE REVIEW

File: modules/react/popup/lib/hooks/useReturnFocus.tsx [hunk 1]
```diff
@@ -14,13 +27,25 @@ import {usePopupModel} from './usePopupModel';
 export const useReturnFocus = createElemPropsHook(usePopupModel)(model => {
   const visible = model.state.visibility !== 'hidden';
 
-  React.useLayoutEffect(() => {
+  React.useEffect(() => {
```
Comment (NicholasBoll) [inline modules/react/popup/lib/hooks/useReturnFocus.tsx:30]: `useEffect` must be used for `document.activeElement` to be the correct element. `useLayoutEffect` happens before the browser shifts focus.

The downside is there may be a frame rendered by the browser where the target element doesn't have focus. The upside is we can add extra heuristics to determine if the user clicked on a focusable element (we should not change focus in this case).

File: modules/react/common/lib/utils/elements.ts [hunk 2]
```diff
@@ -2,7 +2,7 @@
  * Is an element focusable? This function performs various tests to see if the element in question
  * can receive focus. Should skip disabled elements as they are not focusable.
  */
-export const isFocusable = (element: HTMLElement) => {
+export const isFocusable = (element: Element) => {
```
Comment (NicholasBoll) [inline modules/react/common/lib/utils/elements.ts:5]: Turns out I can make this type more permissive which helps for some callers that use `Element` instead of `HTMLElement`

File: modules/react/common/lib/utils/elements.ts [hunk 3]
```diff
@@ -35,7 +35,11 @@ export const getFirstFocusableElement = (container: HTMLElement): HTMLElement |
 
   for (let i = 0; i < elements.length; i++) {
     const element = elements.item(i);
-    if (element && isFocusable(element as HTMLElement)) {
+    if (
+      element &&
+      isFocusable(element as HTMLElement) &&
```
Comment (mannycarrera4) [inline modules/react/common/lib/utils/elements.ts:40]: Do you still need to cast it as HTMLElement?

**Comment by mannycarrera4** [comment]
Only thing I'm not sure of the intended behavior. If I open the popup and try to tab, and I tab out of the close button, what is the expected behavior?

File: modules/react/common/lib/utils/elements.ts (hunk 3 above)
Comment (NicholasBoll) [reply modules/react/common/lib/utils/elements.ts:40]: No, we do not. Nice catch

File: modules/react/popup/lib/hooks/useReturnFocus.tsx [hunk 4]
```diff
@@ -30,19 +57,62 @@ export const useReturnFocus = createElemPropsHook(usePopupModel)(model => {
...
+  // next focusable element. This means that the `useFocusRedirect` will change focus back to the
+  // target, then the tab key is processed by the browser to focus on the next item after the target
+  // without us having to use a focus manager to guess what the next focusable element is.
+  //
+  // But because we're using `useLayoutEffect` instead of `useEffect`, we cannot use
+  // `document.activeElement` (because the focus hasn't changed yet because the browser hasn't
+  // triggered a default action yet) to determine if a user clicked on something that can accept
+  // focus itself. If we don't short-circuit return focus, the user will intend to click on an
+  // `input` element only to get focus changed back. This is annoying to users and unintuitive. Instead,
+  // we'll use `mousedown` and `mouseup` to determine if we're closing because of a mouse click.
```
Comment (mannycarrera4) [inline modules/react/popup/lib/hooks/useReturnFocus.tsx:84]: Do we have to account for `blur` events or does mouse down and up cover our cases?

**Review by mannycarrera4 — APPROVED** [review]
Looks good to me! Had a question on the math we're doing to calculate element height vs scroll parent and some reasoning behind it!
