### PR TITLE
docs: Fix prop tables. Also add spec table to Modal

### LINKED ISSUE #1126: createComponent components no longer work with react-docgen-typescript
## 🐛 Bug Report

We're starting to rely more heavily on MDX (and automatically generated prop tables). At some point in the development of v5, the compatibility with react-docgen-typescript has been broken. Now, the prop table only displays the props that `createComponent` accounts for (`ref` and `as`)

## To Reproduce

Render a component in the prop table (e.g. `<ArgsTable of={IconButton} />`)

## Expected Behavior

All props should be rendered.

## Actual Results

Only `ref` and `as` are listed.

### PR DESCRIPTION
**Pull request by NicholasBoll**
Fixes #1126

### CODE REVIEW

**Review by jamesfan — APPROVED** [review]
Spot-checked `ArgsTables` for several components -- all props seem to be displaying properly now. 👍

File: modules/react/modal/stories/examples/CustomFocus.tsx [hunk 1]
```diff
@@ -1,10 +1,9 @@
 import React from 'react';
-import {Modal} from '@workday/canvas-kit-react/modal';
+import {Modal, useModalModel} from '@workday/canvas-kit-react/modal';
 import {DeleteButton} from '@workday/canvas-kit-react/button';
 import FormField from '@workday/canvas-kit-react/form-field';
 import TextInput from '@workday/canvas-kit-react/text-input';
 import {HStack} from '@workday/canvas-kit-labs-react';
-import {useModalModel} from '../../lib/hooks';
```
Comment (NicholasBoll) [inline modules/react/modal/stories/examples/CustomFocus.tsx:7]: Ooops. Autoimport mistake

File: modules/react/tokens/stories/stories.tsx [hunk 2]
```diff
@@ -116,7 +116,7 @@ const SizeLabel = styled('div')({
 export const BorderRadius = () => (
   <React.Fragment>
     {Object.keys(borderRadius).map(size => (
-      <div css={{display: 'flex'}}>
+      <div css={{display: 'flex'}} key={size}>
```
Comment (NicholasBoll) [inline modules/react/tokens/stories/stories.tsx:119]: Fixes key warnings in the console.
