### PR TITLE
fix(drawer): Add support for word wrapping in IE11

### LINKED ISSUE #878: word-break: 'break-word' is not supported in IE11
## 🐛 Bug Report

`Drawer` uses `wordBreak: 'break-word',` which is not supported by IE11. We should pair it with `wordWrap: 'break-word',`

## To Reproduce

Add long text in the Drawer component, and open up an IE11 browser.

## Expected Behavior

Long words / and text should wrap in the drawer in IE11

## Actual Results

There is no text wrapping. 😢 

## Browser (if applicable)

IE11

### Error Output

Screen Shot 2020-10-08 at 4 38 12 PM

### Correct Output

Screen Shot 2020-10-08 at 4 37 48 PM

### PR DESCRIPTION
**Pull request by alanbsmith**
## Issue

Fixes #878 

## Overview

This PR adds IE11 support for word wrapping in the Drawer component.

## Where Should the Reviewer Start?

`modules/_labs/drawer/react/lib/Drawer.tsx`

## Testing Manually

* Pull down changes
* Run `yarn start`
* visit `http://localhost:9001/?path=/story/testing-react-labs-drawer--drawer-states`
* update the text in one of the drawers
  * I would recommend something like "Note: Internet_Explorer_Eleven was originally released in October 2013"
* See "Internet_Explorer_Eleven" as expected

## New Dependencies

n/a

## Screenshots (if applicable)

See screenshots in #878 

## Thank You Gif
_Share a fun [gif](https://giphy.com) to say thanks to your reviewer:_

dog wrapping itself up in a blanket

## Checklist

- [ ] branch has been rebased on the latest master commit
- [ ] tests are changed or added
- [ ] `yarn test` passes
- [ ] all (dev)dependencies that the module needs is added to its `package.json`
- [ ] code has been documented and, if applicable, usage described in README.md
- [ ] module has been added to `canvas-kit-react` and/or `canvas-kit-css` universal modules, if
      applicable
- [ ] design approved final implementation
- [ ] a11y approved final implementation
- [ ] code adheres to the [API & Pattern guidelines](../API_PATTERN_GUIDELINES.md)

### CODE REVIEW

File: modules/toast/react/lib/Toast.tsx [hunk 1]
```diff
@@ -69,7 +69,7 @@ const ActionButton = styled('button')({
 
 const Message = styled('div')({
   wordBreak: 'break-word',
-  wordWrap: 'break-word',
+  wordWrap: 'break-word', // Needed for IE11
```
Comment (alanbsmith) [inline modules/toast/react/lib/Toast.tsx:72]: Added this as a clarification, so it won't be accidentally removed.

**Review by NicholasBoll — APPROVED** [review]
