### PR TITLE
fix: Extend component props with correct interfaces

### LINKED ISSUE #162: Fix incorrect extensions of HTMLAttributes
## 🐛 Bug Report

When we're extending props to contain attributes from HTML elements, we're currently using the type `React.HTMLAttributes<T>`. For some components we should be using a more specific type of `HTMLAttributes`. For example, when we're spreading element props to an `<input>` from the component (you'll see this as: `...elemProps`) we need to be more specific about the type of attributes. We are already doing this in some places correctly: `extends React.InputHTMLAttributes<HTMLInputElement>`.

Note:
There are a lot of resources on the web that specify that we use `HTMLProps` to extend our prop interfaces. This doesn't seem correct, it's too generic. `HTMLProps` contains `AllHTMLAttributes<T>` and `ClassAttributes<T>`. This makes me think that it's less for extending prop interfaces and more for describing props for HTML elements.

## To Reproduce

1. Add the `name` prop to `Checkbox`. It is an `<input>` that incorrectly extends `HTMLAttributes<HTMLInputElement>`
2. You'll get a TS error

## Actual Results

A clear and concise description of what actually happens

## Browser (if applicable)

If this was a visual bug, what browser did you spot it on?

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/htmlattributes-vs-htmlprops-d34n9

### Error Output

Screen Shot 2019-08-30 at 11 28 01 AM

### PR DESCRIPTION
**Pull request by lychyi**
## Summary

Fixes #162

## Checklist

- [x] branch has been rebased on the latest master commit
- [ ] tests are changed or added
- [x] `yarn test` passes
- [ ] all (dev)dependencies that the module needs is added to its `package.json`
- [ ] code has been documented and, if applicable, usage described in README.md
- [ ] module has been added to `canvas-kit-react` and/or `canvas-kit-css` universal modules, if
      applicable
- [ ] design approved final implementation
- [ ] a11y approved final implementation
- [x] code adheres to the [API & Pattern guidelines](../API_PATTERN_GUIDELINES.md)

### CODE REVIEW

File: modules/banner/react/lib/Banner.tsx [hunk 1]
```diff
@@ -6,7 +6,7 @@ import {SystemIcon} from '@workday/canvas-kit-react-icon';
 import {exclamationCircleIcon, exclamationTriangleIcon} from '@workday/canvas-system-icons-web';
 import {focusRing} from '@workday/canvas-kit-react-common';
 
-export interface BannerProps extends React.HTMLAttributes<HTMLButtonElement> {
+export interface BannerProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
```
Comment (NicholasBoll) [inline modules/banner/react/lib/Banner.tsx]: Ah. Now I understand what you mean. I guess I assumed `HTMLAttributes<HTMLButtonElement>` would automatically apply attributes from `HTMLButtonElement`, but I see that it doesn't.

Comment (NicholasBoll) [reply modules/banner/react/lib/Banner.tsx]: I think we should use or make a lint rule to help with this. I see a pattern where the Element type should match the React element interface.

Comment (lychyi) [reply modules/banner/react/lib/Banner.tsx]: @NicholasBoll Not all React Elements match the interface for that element. `HTMLAttributes<HTMLSpanElement>` is a good example... it's not `SpanHTMLAttributes<HTMLSpanElement>`.

It can be a lint rule or maybe we can make an indexable type so that it's maintained in one place? Something like:

```
// shared/types.ts

interface ElementProps {
  body: ...,
  br: ...,
  button: React.ButtonHTMLAttributes<HTMLButtonElement>,
  canvas: ...
  ...
}

// banner/react/Banner.tsx

type ButtonElementProps = ElementProps['button'];
export interface BannerProps extends ButtonElementProps {
  ...
}
