### PR TITLE
fix(layout): Compensate column width calculations

### LINKED ISSUE #205: Layout/Column Grid not sizing inner cells correctly
## 🐛 Bug Report

Building a `<Layout>` with `<Layout.Column columns=4>` with Images have a width of 100% in each cell, The center column is a smaller width than the outer columns because of inner padding.

## To Reproduce

Create a `<Layout>` with `<Layout.Column columns=4>` and put `` tags with widths of 100%.

## Expected Behavior

All cells should be the same width and be spaced correctly.

## Actual Results

Cells along the center column have smaller widths than cells in the outermost columns.

## Browser (if applicable)

Chrome

image

### PR DESCRIPTION
**Pull request by sahlhoff**
## Summary

Fixes #205  and #125 

See [CodeSandbox Example](https://codesandbox.io/s/canvas-kit-issue-reproduction-oeqer?fontsize=14). You will notice the miss-alignment of the last two rows.

## Checklist

- [x] branch has been rebased on the latest master commit
- [x] tests are changed or added
- [x] `yarn test` passes
- [x] all (dev)dependencies that the module needs is added to its `package.json`
- [x] code has been documented and, if applicable, usage described in README.md
- [x] module has been added to `canvas-kit-react` and/or `canvas-kit-css` universal modules, if
      applicable
- [ ] design approved final implementation
- [ ] a11y approved final implementation
- [ ] code adheres to the [API & Pattern guidelines](../API_PATTERN_GUIDELINES.md)

## Additional References

Why do we need to subtract compensation from the widths?

The width of columns without siblings are calculated incorrectly. We need to proportionally apply a reduction to the widths of columns for the potentially missing padding of the sibling column. 

A potentially easier way to think of this would be to remove the spacing from the parent container and then doing the width percentage calculation. We are effectively doing this at the `Column` level with these lines:

```tsx
        const compensation = ((12 - columns) / 12) * (spacing! * 2);
        return {width: `calc(${(columns / 12) * 100}% - ${compensation}px)`}; 
```

### CODE REVIEW

File: modules/layout/react/lib/Layout.tsx [hunk 1]
```diff
@@ -53,9 +53,14 @@ const LayoutContainer = styled('div')<LayoutProps>(
...
 );
 
+export function stripUnit(value: string): number {
+  return parseInt(`${value}`.replace('px', ''), 10);
+}
+
 export default class Layout extends React.Component<LayoutProps> {
   static defaultProps = {
     gutter: canvas.spacing.xs,
+    spacing: stripUnit(canvas.spacing.xs),
```
Comment (sahlhoff) [inline modules/layout/react/lib/Layout.tsx]: Not 100% sure if this is the correct way to handle the default spacing for a child. What I am attempting to do is have the child spacing have a default value of `canvas.spacing.xs` But with the ability to override it at the `Layout` and `Column` level like this:

```tsx
       <Layout spacing={60}>
          <Layout.Column spacing={0}>
            <Card heading="Custom Spacing (0px)" />
          </Layout.Column>
          <Layout.Column>
            <Card heading="Custom Spacing (60px)" />
          </Layout.Column>
          <Layout.Column>
            <Card heading="Custom Spacing (60px)" />
          </Layout.Column>
        </Layout>
```

I found that if I set the default spacing in `Column` instead of the `Layout` [this check](https://github.com/Workday/canvas-kit/blob/eed62cf9591dc97fd98c305ac96caeb42acc0da9/modules/layout/react/lib/Layout.tsx#L76) would always be true.

File: modules/layout/react/lib/Column.tsx [hunk 2]
```diff
@@ -35,19 +34,20 @@ const ColumnContainer = styled('div')<ColumnProps>(
...
     if (width) {
       return {width};
     }
 
     if (columns) {
-      return {width: `${(columns / 12) * 100}%`};
+      if (columns === 12) {
+        return {width: `100%`};
+      } else {
+        const compensation = ((12 - columns) / 12) * (spacing! * 2);
```
Comment (lychyi) [inline modules/layout/react/lib/Column.tsx]: I may be reading this wrong but doesn't this mean that `compensation` can be `NaN` if we don't define spacing?

File: modules/layout/react/lib/Layout.tsx (hunk 1 above)
Comment (lychyi) [inline modules/layout/react/lib/Layout.tsx]: I think you can use `spacingNumbers.xs` from `core` here instead of recalculating it.

File: modules/layout/react/lib/Column.tsx (hunk 2 above)
Comment (NicholasBoll) [reply modules/layout/react/lib/Column.tsx]: Javascript is weird...

```ts
1 * null // 0
```

Comment (NicholasBoll) [reply modules/layout/react/lib/Column.tsx]: But I would suggest the following to not rely on this quirk:
```suggestion
        const compensation = ((12 - columns) / 12) * (spacing || 0 * 2);
```

Comment (NicholasBoll) [reply modules/layout/react/lib/Column.tsx]:
```ts
1 * undefined // NaN
```

Comment (sahlhoff) [reply modules/layout/react/lib/Column.tsx]: Updated! Ended up having to add in extra parentheses– 

```tsx
const compensation = ((12 - columns) / 12) * ((spacing || 0) * 2);
```

File: modules/layout/react/lib/Layout.tsx [hunk 3]
```diff
@@ -81,7 +82,7 @@ export default class Layout extends React.Component<LayoutProps> {
   };
 
   public render() {
-    const {children, spacing, gutter, capWidth, ...elemProps} = this.props;
+    const {children, gutter, capWidth, ...elemProps} = this.props;
 
     return (
       <LayoutContainer gutter={gutter} capWidth={capWidth} {...elemProps}>
```
Comment (lychyi) [inline modules/layout/react/lib/Layout.tsx]:
```suggestion
      <LayoutContainer gutter={gutter} capWidth={capWidth}>
```

I know we didn't do this before but it should be best practice that we destructure all props and then use them as needed.

File: modules/layout/react/lib/Column.tsx (hunk 2 above)
Comment (NicholasBoll) [reply modules/layout/react/lib/Column.tsx]: Cool. I had parenthesis in originally and did some light testing and removed it.

File: modules/layout/react/lib/Layout.tsx (hunk 3 above)
Comment (sahlhoff) [reply modules/layout/react/lib/Layout.tsx]: Shouldn't we be spreading the props here thought? This will fail tests for `data-propspread` attribute test

Comment (lychyi) [reply modules/layout/react/lib/Layout.tsx]: Oof you're right. I lost track of this one, I'll re-review and try to get this one in today. So sorry about that.
