### PR TITLE
fix(color-picker): Prevent enter key fowarding to next focus target

### LINKED ISSUE #760: ColorPicker keyDown -> keyPress
## 🐛 Bug? Report

Not exactly a bug, more of a request to change behavior.

The request is to make [this change](https://github.com/Workday/canvas-kit/compare/master...davvidbaker:patch-1) to the color picker hex input behavior. (Use keypress instead of keydown for submission from the hex text input.)

## To Reproduce

The problem with keydown arises in the context of a text editor. We are responding to the `onColorChange` callback by re-focusing the text editor, but the `Enter` keypress event gets fired after the text editor has refocused, resulting in a new line. Changing the color picker text input to respond to the `Enter` keypress instead of keydown would fix this problem.

Here's a gif and sandbox illustrating the problem.
keydown-color

[Sandbox](https://codesandbox.io/s/magical-hooks-g9poq?file=/src/App.js)

If this is not a change y'all would make, do you have a recommended alternative solution?

### PR DESCRIPTION
**Pull request by NicholasBoll**
Fixes #760

## Summary

The original implementation used keydown to detect the "Enter" key and fire the `onColorChange` event. If focus is transferred during the timing of this event, the enter key will actually be forwarded to the next target. This isn't exactly what we want.

This PR moves the custom color input into a `form` element and uses the submit event to handle special functionality like the enter key. This is a more accessible option.

## Checklist

- [x] branch has been rebased on the latest master commit
- [x] tests are changed or added
- [x] `yarn test` passes
- [x] all (dev)dependencies that the module needs is added to its `package.json`
- [x] code has been documented and, if applicable, usage described in README.md

### CODE REVIEW

File: modules/_labs/color-picker/react/lib/ColorPicker.tsx [hunk 1]
```diff
@@ -117,6 +122,7 @@ const isCustomColor = (colors: string[], hexCode?: string) => {
 const ColorPicker = ({
   colorSet = defaultColors,
   customHexInputLabel = 'Custom Hex Color',
+  submitLabel = 'Submit',
```
Comment (NicholasBoll) [inline modules/_labs/color-picker/react/lib/ColorPicker.tsx:125]: I'm not sure why this label was shared with the input. The label didn't describe the functionality any different than the input. This also made it harder to test.

File: modules/_labs/color-picker/react/lib/ColorPicker.tsx [hunk 2]
```diff
@@ -29,14 +29,19 @@ export interface ColorPickerProps extends React.HTMLAttributes<HTMLDivElement> {
...
+  /**
+   * The label of the custom hex color submit icon button.
+   * @default 'Submit'
+   */
+  submitLabel?: string;
   /**
    * The function called when the submit icon is clicked.
    */
-  onSubmitClick?: (event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void;
+  onSubmitClick?: (event: React.FormEvent) => void;
```
Comment (jamesfan) [inline modules/_labs/color-picker/react/lib/ColorPicker.tsx:44]: This change should also be reflected in the README (duplicate documentation strikes again).
