### PR TITLE
fix(tokens): Fixes color token exports

### LINKED ISSUE #1109: TS Error with Color Tokens
## 🐛 Bug Report

The problem is [here](https://github.com/Workday/canvas-kit/blob/master/modules/react/tokens/index.ts#L25).
TLDR: The semantic colors has a colors key, and we’re exporting the default of colors as colors so it’s always being overwritten.

## To Reproduce

* Using TS ^3.9.9
* Look at `modules/react/tokens/index.ts`
* See the error

## Expected Behavior

Color tokens shouldn't be overwriting one another

## Actual Results

TS is angry.

## Browser (if applicable)

n/a

## Link to repl or repo (highly encouraged)

n/a

### Error Output

```bash
27   colors,
node_modules/@workday/canvas-kit-react/tokens/index.ts:27:3 - error TS2783: 'colors' is specified more than once, so this usage will be overwritten.
33   ...semanticColors,
node_modules/@workday/canvas-kit-react/tokens/index.ts:33:3
This spread always overwrites this property.
```

or

Include a screenshot of a visual bug

### PR DESCRIPTION
**Pull request by alanbsmith**
## Summary

Resolves #1109

Previously we were parsing out colors from `canvas-colors-web` like this:

```ts
const {default: colors, gradients, ...semanticColors} = canvasColorsWeb;
```

And exporting them from a default `canvas` object like this:

```ts
const canvas = {
  colors,
  depth,
  space,
  type,
  fontFamily,
  monoFontFamily,
  ...semanticColors,
};
```

TS throws an error because `...semanticColors` has a `color` key which is overwrites the default export. This happened to work because the colors in the default export and the `colors` key were identical.

To resolve this, we're removing the default export and explicitly import each color key.

## Checklist

- [ ] branch has been rebased on the latest master commit
- [ ] tests are changed or added
- [ ] `yarn test` passes
- [ ] all (dev)dependencies that the module needs is added to its `package.json`
- [ ] code has been documented and, if applicable, usage described in README.md
- [ ] module has been added to `canvas-kit-react` and/or `canvas-kit-css` universal modules, if
      applicable
- [ ] design approved final implementation
- [ ] a11y approved final implementation
- [ ] code adheres to the [API & Pattern guidelines](../modules/docs/mdx/API_PATTERN_GUIDELINES.mdx)

### CODE REVIEW

File: modules/react/tokens/index.ts [hunk 1]
```diff
@@ -22,15 +33,21 @@ import {type,
...
-  type,
   fontFamily,
+  iconColors,
+  inputColors,
   monoFontFamily,
-  ...semanticColors,
+  space,
+  statusColors,
+  type,
+  typeColors,
```
Comment (alanbsmith) [inline modules/react/tokens/index.ts:50]: I also alphabetized this list to make it easier to find things.

File: modules/react/tokens/index.ts [hunk 2]
```diff
@@ -1,4 +1,15 @@
...
+  chartingColorOffsets,
+  chartingColors,
+  colors,
+  commonColors,
+  gradients,
+  iconColors,
+  inputColors,
+  statusColors,
+  typeColors,
+} from '@workday/canvas-colors-web';
```
Comment (alanbsmith) [inline modules/react/tokens/index.ts:12]: It seemed odd to me that `gradients` is the only color key excluded from tokens `canvas` default export. Was this intentional? Was it a mistake? I left it out of the export, but we could add it back without it being a breaking change.

Comment (alanbsmith) [reply modules/react/tokens/index.ts:12]: E.g. Why is `canvas.chartingColorOffsets` a thing, but not `canvas.gradients`?

Comment (anicholls) [reply modules/react/tokens/index.ts:12]: Yeah, I'd say it's worth adding 👍  Not sure why it got left out

**Review by anicholls — APPROVED** [review]
