### PR TITLE
fix: Popup/Modal responsiveness with setting max width

### LINKED ISSUE #434: Modal is not responsive on small screens
## 🐛 Bug Report

This is the design of the modal for various screen sizes. The `Modal` component is missing mobile styling.

https://www.figma.com/file/T6ZEio9U0G9IjIvRzpC1Za/Modals?node-id=60%3A130

## Expected Behavior

Modal should be responsive

### PR DESCRIPTION
**Pull request by alexandrzavalii**
## Summary
We need to make popup responsive for mobile and desktop devices.
Fixes #434
The Modal is a Popup wrapped in an overlay, that is why the changes will apply to the Modal as well
**Note:** Closing button will always stay in the popup for now
responsive popup

## Checklist

- [x] branch has been rebased on the latest master commit
- [x] tests are changed or added
- [x] `yarn test` passes
- [x] design approved final implementation
- [x] code adheres to the [API & Pattern guidelines](../API_PATTERN_GUIDELINES.md)

### CODE REVIEW

File: modules/popup/react/stories/stories.tsx [hunk 1]
```diff
@@ -80,4 +81,27 @@ storiesOf('Components|Popups/Popup/React', module)
...
+        <Button onClick={() => null} variant={Button.Variant.Secondary}>
+          Cancel
+        </Button>
+      </Popup>
+    ),
+    {
+      chromatic: {
+        viewports: [320],
+        pauseAnimationAtEnd: true,
+      },
```
Comment (NicholasBoll) [inline modules/popup/react/stories/stories.tsx]: Nice visual story! This is actually the first one to capture a popup and something responsive!

File: cypress/fixtures/example.json [hunk 2]
```diff
@@ -0,0 +1,5 @@
+{
+  "name": "Using fixtures to represent data",
```
Comment (NicholasBoll) [inline cypress/fixtures/example.json]: It is annoying how Cypress continues to add this file... If we don't accept this file, it may just come back in another PR

Comment (alexandrzavalii) [reply cypress/fixtures/example.json]: did not even notice :D
