### PR TITLE
fix(popup): Remove ref fowarding requirement in Popup.Target

### LINKED ISSUE #1114: Remove the requirement for forwarding refs for custom popup targets
## Motivation

It is common to use custom target elements for `Popup`, `Dialog`, and `Modal`. But for correct accessibility, ref forwarding is required which is not very common outside of library code. The required `ref` can instead be set using `onClick`. The only reason we require ref forwarding now is for the edge case where the application programmatically open a Popup without the user interacting first. In this case, without the `ref`, the popup appears at the top-left of the screen since PopperJS doesn't have a reference to an element to appear around.

## Example

```tsx
const MyTarget = ({...props}: React.HTMLButtonAttributes<HTMLButtonElement>) => {
  <button {...props}>Open</button>
}

const App = () => {
  return (
    <Modal>
      <Modal.Target as={MyTarget} />
      ...
    </Modal>
  )
}
```

Without this feature, `MyTarget` would have to use `React.forwardRef`

### PR DESCRIPTION
**Pull request by NicholasBoll**
- Remove ref forwarding requirement in `Popup.Target`, `Modal.Target`, and `Dialog.Target`
- Add examples to show using custom targets for `Popup` and `Modal`
- Add Cypress specifications for new examples

Fixes #1114

### CODE REVIEW

File: modules/react/modal/stories/examples/CustomTarget.tsx [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+      <Modal.Overlay>
+        <Modal.Card>
+          <Modal.CloseIcon aria-label="Close" />
+          <Modal.Heading>Modal</Modal.Heading>
+          <Modal.Body>Contents</Modal.Body>
+        </Modal.Card>
+      </Modal.Overlay>
+    </Modal>
+  );
+};
```
Comment (mannycarrera4) [inline modules/react/modal/stories/examples/CustomTarget.tsx:26]: YASSS thank you!

**Review by mannycarrera4 — APPROVED** [review]
Thanks for working through this with me and coming up with a solution!
