### PR TITLE
fix(popup): Fix useReturnFocus to respect tabindex=-1 buttons

### LINKED ISSUE #3140: Return Focus doesn't respect buttons with a tabindex of -1
## 🐛 Bug Report

The `useReturnFocus` hook does not respect buttons with a `tabindex` of `-1`. These buttons are focusable via mouse/touch, but not via keyboard. If one of these buttons is clicked, focus should go to that button that was clicked and not the return focus target.

If you click on a button with a `tabindex` of `-1`, the focus ring will go to the button for a frame, then the focus is redirected to the popup's target.

### Error Output

Image

### PR DESCRIPTION
**Pull request by NicholasBoll**
## Summary

Separate the concept of focusability between keyboard and mouse. Buttons with a `tabindex` of `-1` are focusable via a pointer device, but not via a keyboard. A user clicking on a button that isn't focusable by keyboard is still a valid target for avoiding focus stealing.

Fixes #3140

Fixes: #1234 

## Release Category
Components

---

## For the Reviewer

- [x] PR title is short and descriptive
- [x] PR summary describes the change (Fixes/Resolves linked correctly)

## Where Should the Reviewer Start?

Test

## Areas for Feedback? (optional)

- [ ] Code
- [ ] Testing

## Testing Manually

Go to the `ReturnFocusTest` and open the popup and click on the tabindex button. The Cypress Test also does this.

### CODE REVIEW

File: modules/react/button/lib/BaseButton.tsx [hunk 1]
```diff
@@ -169,7 +169,7 @@ export const buttonStencil = createStencil({
       opacity: cssVar(buttonColorPropVars.default.opacity, cssVar(opacity, system.opacity.full)),
     },
     // Focus Styles
```
Comment (mannycarrera4) [inline modules/react/button/lib/BaseButton.tsx:171]: wow, really?

File: modules/react/button/lib/BaseButton.tsx [hunk 2]
```diff
@@ -169,7 +169,7 @@ export const buttonStencil = createStencil({
...
-    '&:focus-visible, &.focus': {
+    '&:focus, &.focus': {
```
Comment (mannycarrera4) [inline modules/react/button/lib/BaseButton.tsx:172]: is this a breaking change? I thought we moved away from `:focus` to `focus-visibile`.

**Review by mannycarrera4 — APPROVED** [review]
