### PR TITLE
fix(tabs): Remove event.preventDefault from TabList

### LINKED ISSUE #968: [v4][Tabs] Click action is prevented from being propagated within TabList via default key actions
## 🐛 Bug Report

In v4 of `Tabs`, the click action is prevented from being propagated within TabList via default key actions

## To Reproduce

* Have a control nested within a `<Tabs.Item>` 
* Focus the nested control (e.g. a button) via keyboard navigation
* Attempt to trigger the click action via space key

## Expected Behavior

Trigger the click event of the element.

## Actual Results

Click event is not triggered. 

## Link to repl or repo (highly encouraged)

https://github.com/Workday/canvas-kit/blob/master/modules/_labs/tabs/react/lib/TabList.tsx#L52
a PR that includes a fix to this issue is already out for v5 -- #953  (courtesy of @NicholasBoll 🙇 )

Screen Shot 2021-02-11 at 11 41 30 AM

### PR DESCRIPTION
**Pull request by NicholasBoll**
Fixes #968

### CODE REVIEW

File: modules/_labs/tabs/react/lib/TabList.tsx [hunk 1]
```diff
@@ -46,11 +46,6 @@ const TabList = ({children, ...elemProps}: TabListProps) => {
       case 'End':
         setIntentTab('last');
         break;
-      case 'Enter':
-      case ' ':
-        setActiveTab(intentTab);
-        event.preventDefault(); // prevent clicking this button
-        break;
```
Comment (NicholasBoll) [inline modules/_labs/tabs/react/lib/TabList.tsx:53]: This is the real fix. Everything else is to get Cypress tests passing again. I went through the same thing in the Tabs PR: #910

**Review by alanbsmith — APPROVED** [review]
🦊
