### PR TITLE
fix: Combobox and search bar not in container

### LINKED ISSUE #476: Header search form not filling to width
## 🐛 Bug Report

_I added a red border to fully illustrate the issue_. 
Screen Shot 2020-02-19 at 11 49 06 AM
Screen Shot 2020-02-19 at 11 49 18 AM
The search bar does not properly fill its width. As a result it cannot be properly styled when imported, and it cannot be properly centered in a container without having to add margins to adjust for the "gap."

## To Reproduce

Inspect the search form, try to add styles to it, notice the width problem

## Expected Behavior

I expect the search form to the fill the width it's expected to be.

## Actual Results

The search form does not fill the width.

## Browser (if applicable)

Chrome, macos

### PR DESCRIPTION
**Pull request by vibdev**
## Summary
This PR fixes #476 as well as an issue in collapsed mode where the input is too low

Screen Shot 2020-03-12 at 12 25 15 PM
Screen Shot 2020-03-12 at 12 12 57 PM

I tweaked the story for combobox to catch a regression but it requires autofocus to be set on the input let me know if that can cause issues in automation.

This is a possible alternative to https://github.com/Workday/canvas-kit/pull/485

## Checklist

- [x] branch has been rebased on the latest master commit
- [x] tests are changed or added
- [x] `yarn test` passes
- [x] all (dev)dependencies that the module needs is added to its `package.json`
- [x] code has been documented and, if applicable, usage described in README.md
- [x] design approved final implementation
- [x] a11y approved final implementation
- [x] code adheres to the [API & Pattern guidelines](../API_PATTERN_GUIDELINES.md)

### CODE REVIEW

File: modules/_labs/combobox/react/lib/Combobox.tsx [hunk 1]
```diff
@@ -104,8 +104,9 @@ const ResetButton = styled(IconButton)<{shouldShow: boolean}>(
   {
     width: spacing.l,
     height: spacing.l,
-    margin: `-${spacing.s}`,
-    left: `-${spacing.m}`,
+    position: `absolute`,
```
Comment (alexandrzavalii) [inline modules/_labs/combobox/react/lib/Combobox.tsx]: nit: `position: 'absolute';`

File: modules/_labs/combobox/react/stories/stories.tsx [hunk 2]
```diff
@@ -44,8 +44,9 @@ class Autocomplete extends React.Component<
         labelId="autocomplete-123"
         onFocus={action(`Focus`)}
         onBlur={action(`Blur`)}
+        initialValue={`Test`}
```
Comment (alexandrzavalii) [inline modules/_labs/combobox/react/stories/stories.tsx]: would this work? initialValue='Test'

Comment (vibdev) [reply modules/_labs/combobox/react/stories/stories.tsx]: moved to single quotes more consistently
